### PR TITLE
Update englishDataset phrases

### PR DESCRIPTION
**Pull request by HatScripts**
**Type of change:**

- [x] Refactor
- [ ] Performance improvement
- [x] New feature
- [ ] Bug fix
- [ ] Other (please describe):

**Please describe the changes this PR makes and why it should be merged:**

1. Sorted phrases alphabetically
2. Add 10 new phrases: `bollocks`, `dyke`, `kike`, `negro`, `piss`, `prick`, `spastic`, `turd`, `twat`, `wanker`
    (Found at: https://en.wiktionary.org/wiki/Category:English_swear_words)
4. Update patterns for `abbo` (now [`abo`](https://en.wiktionary.org/wiki/abo#English)), `bestiality`, and `cunt`

**Status:**

- [ ] I've added/modified unit tests relevant to my change / not needed
- [ ] This PR contains breaking changes
- [ ] This PR doesn't include changes to the code

### CODE REVIEW

**Review by jo3-l — CHANGES_REQUESTED** [review]
Would you mind retargetting this PR to the dev branch? Everything else LGTM, thanks.

**Comment by HatScripts** [comment]
> Would you mind retargetting this PR to the dev branch? Everything else LGTM, thanks.

Done! :)

**Comment by jo3-l** [comment]
Thanks, I'll fix the lint issues in a followup commit.

**Comment by HatScripts** [comment]
Any chance of this being added to the main branch?

**Comment by jo3-l** [comment]
Thanks for the reminder. I will tag a new release this weekend.

**Comment by jo3-l** [comment]
Released 0.2.1 on npm, PTAL @HatScripts.

**Pull request merged**
