### PR TITLE
Add a blacklist for randomCharFromSetCensorStrategy

### LINKED ISSUE #82: bug: grawlixCensorStrategy sometimes generates "@$$"
### Expected behavior

Censoring strategy should generate a replacement string that itself does not contain any profanity. However, since grawlixCensorStrategy returns a string of random characters that include "@" and "$", sometimes it generates "@$$", which is considered profanity by the default englishDataset/englishRecommendedTransformers matcher recommended in the guide.

### Actual behavior

This causes TextCensor with the default settings to sometimes replace "ass" or "@$$" with "@$$".

### Minimal reproducible example

```typescript
const {
	RegExpMatcher,
	TextCensor,
	englishDataset,
	englishRecommendedTransformers,
} = require('obscenity');

const matcher = new RegExpMatcher({
	...englishDataset.build(),
	...englishRecommendedTransformers,
});

const censor = new TextCensor();
const input = '@$$';
const matches = matcher.getAllMatches(input);
for (let i = 0; i < 100; i++) {
    if (censor.applyTo(input, matches) === input)
        console.log("input did not change after censoring");
}
```

### Steps to reproduce

_No response_

### Additional context

_No response_

### Node.js version

v20

### Obscenity version

v0.4.0

### Priority

- [ ] Low
- [X] Medium
- [ ] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

### PR DESCRIPTION
**Pull request by eltoder**
Fixes #82

**Type of change:**

- [ ] Refactor
- [ ] Performance improvement
- [ ] New feature
- [x] Bug fix
- [ ] Other (please describe):

**Please describe the changes this PR makes and why it should be merged:**

As suggested in #82, make randomCharFromSetCensorStrategy generate a new replacement string if it generated a bad word.

**Status:**

- [x] I've added/modified unit tests relevant to my change / not needed
- [ ] This PR contains breaking changes
- [ ] This PR doesn't include changes to the code

### CODE REVIEW

**Comment by eltoder** [comment]
>I do want to note in passing that this isn't going to catch cases like @$$$

Good point. I can pass a list of patterns, compile them into one regexp, and match against the generated string. Not sure if I should anchor the regexp or not. If not, everything will match as a substring, so `@\$\$` will match `@$$$` and anything else that contains that, including say `%*@$$&*`. If I anchor the regexp, I can use `@+\${2,}`. Not anchoring regexp is easier, but the probability of generating something that matches it actually increases with the length instead of decreasing.

>Sorry for any delay, and if you're hitting this in production you can always use this censor strategy directly in your code until the new version is out.

No problem at all. I don't know if this was even a big deal, but my users reported it. I already changed my app to use `keepStartCensorStrategy(asteriskCensorStrategy())`. Now I think that even that is overengineering and I should just replace everything with one "🤬". Another option a long the same lines is to use [unicode grawlix](https://codeforhire.com/2018/03/12/swearing-in-unicode/), then hope that no one complains about "🌀⚡⚡".

**Comment by jo3-l** [comment]
> Good point. I can pass a list of patterns, compile them into one regexp, and match against the generated string.

Hm. I don't know how comfortable I am with this idea: it feels like we're starting to duplicate the work of the main library (though obviously at a much smaller scale—it's possible this is a slippery slope argument on my part), and I wonder if there is a more general solution. On that note, I discussed this issue briefly with some friends elsewhere and one of them proposed having grawlix never generate the same character twice in a row, which incidentally fixes this issue at the cost of even more complexity. I will have to think about that. In any case, though, please don't let me push this work onto you. Like I said, this PR is a fine stopgap as is.

Unicode grawlix is a very fun idea, though 😁

**Comment by eltoder** [comment]
Yes, it's definitely some duplication of the main library. One other option is then to run the main library on the generated replacement in `applyTo`.

Not generating the same character twice in a row is actually very easy to do as well. Let me know if you like that idea. It's less code than in this PR.

**Comment by jo3-l** [comment]
> Not generating the same character twice in a row is actually very easy to do as well. Let me know if you like that idea. It's less code than in this PR.

I'm happy to try this out. It would be good to have an error in the degenerate case of 1 input codepoint (if avoiding consecutive identical characters is enabled.)

**Comment by jo3-l** [comment]
I'm going to close this in favor of your new PR #85, which generalizes a little better. Thanks for the fruitful discussion.

**Pull request closed without merging**
