### PR TITLE
Update resolve-leetspeak/dictionary.ts

### PR DESCRIPTION
**Pull request by HatScripts**
**Type of change:**

- [ ] Refactor
- [ ] Performance improvement
- [x] New feature
- [ ] Bug fix
- [ ] Other (please describe):

**Please describe the changes this PR makes and why it should be merged:**

Updated the leetspeak dictionary to include:
- `'6'` → `'b'`
- `'8'` → `'b'`
- `'9'` → `'g'`
- `'!'` → `'i'`
- `'5'` → `'s'`
- `'7'` → `'t'`
- `'2'` → `'z'`

Some of these replacements might be overkill, so please let me know what you think.
Further reading: https://en.wikipedia.org/wiki/Leet#Table_of_leet-speak_substitutes_for_normal_letters

**Status:**

- [ ] I've added/modified unit tests relevant to my change / not needed
- [ ] This PR contains breaking changes
- [ ] This PR doesn't include changes to the code

### CODE REVIEW

**Comment by HatScripts** [comment]
Also, I noticed that `sh|t` isn't being censored. Not sure why. Terms like `tw@t` and `c0ck` etc. are correctly being censored.

**Comment by jo3-l** [comment]
Sorry, but I'm not convinced these substitutions are valuable, with the exception of perhaps `! -> i`. When we add back whitespace stripping, for instance, `6 itch` will be flagged as containing `bitch` which seems a rather egregious false positive. I'm sure there are many more examples, so would prefer to err on the side of caution here unless you have a compelling reason otherwise.

**Comment by HatScripts** [comment]
> `6 itch` will be flagged as containing `bitch`

I could be wrong, but to me, this seems like an argument for including `.addWhitelistedTerm('b itch')`, not for excluding the leetspeak.

However, I'm having trouble even finding a word ending in `b` that would appear before the word `itch`. The only thing I can come up with for now is `scab itch`.

**Comment by jo3-l** [comment]
To be clear, my point is that the phrase `6 itch` -- not including the `b` -- will be flagged as containing profanity, because `6` would be remapped to `b`. That seems a clear mistake to me.

**Comment by HatScripts** [comment]
Oh okay, that makes sense. Forgive my confusion.

**Comment by HatScripts** [comment]
Just to clarify, assuming `resolve-leetspeak` is ran before the check for whitelisted terms, wouldn't `.addWhitelistedTerm('b itch')` still be enough in the case of `6 itch` to ignore the false positive?

**Comment by jo3-l** [comment]
> assuming resolve-leetspeak is ran before the check for whitelisted terms

This is not the case; whitelisted term matching runs essentially on the original text by default (with only lowercasing applied.) I am not sure this is something we want to change.

**Comment by jo3-l** [comment]
Per my previous comments I'm not sure this is worth doing, so closing for now. Happy to discuss if you disagree, as always.

**Pull request closed without merging**
